### ISSUE TITLE
Use eza/exa, if available

### ISSUE THREAD

**Issue by kytta** [zimfw/utility#4]
### Is your feature request related to a problem? Please describe.

While this project supports `lsd`, many people use [`eza`](https://github.com/eza-community/eza).

### Describe the solution you'd like

Define the same aliases for `eza` as you do for `lsd`

### Describe alternatives you've considered

Doing it myself, but having this in a plugin that I already source would be better

**Comment by kytta** [comment]
Whoops, didn't notice https://github.com/zimfw/exa

Wouldn't it make sense to merge the two modules?

**Comment by ericbn** [comment]
[zimfw/exa](https://github.com/zimfw/exa) works with both eza and exa.

I prefer to keep the exa module separate from the utility module because eza/exa are not totally compatible with the ls parameters, but lsd is.

**Comment by kytta** [comment]
I see, makes sense!
