### ISSUE TITLE
Illumos/Solaris grep does not support color=auto

### ISSUE THREAD

**Issue by thenktor** [zimfw/utility#5]
### Prerequisites

- [X] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [X] I've checked the zimfw [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [X] I've checked the zimfw [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.

### Bug description

Hi,

on OpenIndiana and OmniOS using grep returns an error:
```
# echo test | grep te
grep: illegal option -- color=auto
usage:  grep [-E|-F] [-bchHilLnoqrRsvx] [-A num] [-B num] [-C num|-num]
             [--label=name] [-e pattern_list]... [-f pattern_file]...
             [pattern_list] [file]...
```

### Steps to reproduce

Use the module on OpenIndiana or OmniOS:
```
# echo $OSTYPE
solaris2.11
```

### Current behavior

error

### Expected behavior

Do not use --color=auto

### zimfw info

```shell
zimfw version:        1.13.1 (built at 2024-04-28 19:07:19 UTC, previous commit is c86223f)
LANG:                 de_DE.UTF-8
OSTYPE:               solaris2.11
TERM:                 xterm-256color
TERM_PROGRAM:
TERM_PROGRAM_VERSION:
ZIM_HOME:             /root/.zim
ZSH_VERSION:          5.9
```

**Comment by ericbn** [comment]
Fixed by #6
